### ISSUE TITLE
Is there Shuffle-BN like moco in your paper?

### ISSUE THREAD

**Issue by UcanSee** [limbo0000/InstanceLoc#3]

**Comment by limbo0000** [comment]
Hi @UcanSee ,

Yes. For the contrastive part, we follow the MoCo to perform the shuffle-BN when pretraining,

**Comment by UcanSee** [comment]
> Hi @UcanSee ,
> 
> Yes. For the contrastive part, we follow the MoCo to perform the shuffle-BN when pretraining,

Thanks for your response，the other thing that's confusing me is the setting of FPN. In my opinion, for a gt box, you assign it to each level of FPN and then get 7*7 features through roi align, finally you compute contrastive loss in each level. Did I get it wrong?  In addition, did the MLP head shared between all levels of FPN?

**Comment by limbo0000** [comment]
Your understanding is right. Besides, the MLP head is shared across different levels.

**Comment by UcanSee** [comment]
I've got it! Thank you very much.
