### ISSUE TITLE
how to calculate the overall loss?

### ISSUE THREAD

**Issue by jisunkwo** [limbo0000/InstanceLoc#5]
Hi, thanks for your interesting works.
I have a question about the loss for r50-fpn.
As I understand, you computed the contrastive loss on roi aligned features of each level and that means 4 losses are computed.
Then how did you combine the losses to get an overall loss, just sum of all losses or weighted sum??

**Comment by limbo0000** [comment]
Hi @jisunkwo,

Thanks for your interest in our work. Yes, we just sum all losses.

**Comment by jisunkwo** [comment]
got it!
Thanks for reply. :)
