### ISSUE TITLE
Unclear what is used as a negative in loss

### ISSUE THREAD

**Issue by MartSlaaf** [limbo0000/InstanceLoc#7]
Hi!

Nice paper. 
Though, it's unclear during the course of paper, what is used as negative examples for the InfoNCE objective. We know what are the v_q and v_k_+, although what is used as v_k_i's is not set. Natural guess supposes it's something like C(J_i, B_i), where J and B are random target and background image. But I can not figure it out for sure, while reading the paper.

**Comment by limbo0000** [comment]
Hi @MartSlaaf ,

Thanks for your interests in our paper. 

The positive pair consists of two foreground images, augmented from the same instance. The negative examples follow the same protocol of MoCo-v2, which stores multiple features in a negative queue. Besides, the negative queue would be also updated during training.

**Comment by MartSlaaf** [comment]
Hi @limbo0000,

Thanks for your answer.

I see now, it's clicked after you pointed it. Although, I would say it's worthy mentioning directly in section 4.1, say, after eq 5,6. Otherwise it's a bit har to bridge this gap. The next mention of this queue, I can note in the paper is around implementation details section. Which is rarely being read as thorough as the method section is.
